spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/capitalh
    username: PDBADMIN
    password: MiPassWord123!
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
server:
  port: 8081
